
#mysql secrets
---
apiVersion: v1
data:
  password: WVVJaWRoYjY2Nw==
kind: Secret
metadata:
  name: mysql-root-pass

---
apiVersion: v1
data:
  password: VG1QY1pqdFJReA==
  username: a29kZWtsb3VkX2FpbQ==
kind: Secret
metadata:
  name: mysql-user-pass

---
apiVersion: v1
data:
  database: a29kZWtsb3VkX2RiOA==
kind: Secret
metadata:
  name: mysql-db-url


