---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-deployment
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30007
  selector:
    app: mysql-deployment
  type: NodePort
status:
  loadBalancer: {}
